apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  labels:
    openchoreo.dev/project: doclet
  name: doclet-frontend
  namespace: default
spec:
  autoDeploy: true
  componentType:
    kind: ClusterComponentType
    name: deployment/web-application
  owner:
    projectName: doclet
  workflow:
    kind: ClusterWorkflow
    name: dockerfile-builder
    parameters:
      docker:
        context: .
        filePath: frontend/Dockerfile
      repository:
        appPath: .
        revision:
          branch: main
        url: https://github.com/lakwarus/doclet

---
apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  labels:
    openchoreo.dev/component: doclet-frontend
    openchoreo.dev/project: doclet
  name: doclet-frontend-workload
  namespace: default
spec:
  dependencies:
    endpoints:
    - component: document-svc
      envBindings:
        address: _DEP_DOCUMENT_SVC_URL
      name: http
      visibility: project
    - component: collab-svc
      envBindings:
        address: _DEP_COLLAB_SVC_URL
      name: ws
      visibility: project
  endpoints:
    http:
      port: 8080
      type: HTTP
      visibility:
      - external
  owner:
    componentName: doclet-frontend
    projectName: doclet

