apiVersion: openchoreo.dev/v1alpha1
kind: Resource
metadata:
  labels:
    openchoreo.dev/project: doclet
  name: doclet-nats
  namespace: default
spec:
  owner:
    projectName: doclet
  type:
    kind: ClusterResourceType
    name: nats

---
