apiVersion: openchoreo.dev/v1alpha1
kind: Resource
metadata:
  labels:
    openchoreo.dev/project: doclet
  name: doclet-postgres
  namespace: default
spec:
  owner:
    projectName: doclet
  parameters:
    database: doclet
  type:
    kind: ClusterResourceType
    name: postgres
---
