apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  labels:
    openchoreo.dev/project: doclet
  name: document-svc
  namespace: default
spec:
  autoDeploy: true
  componentType:
    kind: ClusterComponentType
    name: deployment/service
  owner:
    projectName: doclet
  workflow:
    kind: ClusterWorkflow
    name: dockerfile-builder
    parameters:
      docker:
        context: .
        filePath: services/document/Dockerfile
      repository:
        appPath: .
        revision:
          branch: main
        url: https://github.com/lakwarus/doclet

---
apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  labels:
    openchoreo.dev/component: document-svc
    openchoreo.dev/project: doclet
  name: document-svc-workload
  namespace: default
  resourceVersion: "66607352"
  uid: b6bedff7-fd4e-487d-b46e-b23c9d540158
spec:
  container:
    image: 237632677974.dkr.ecr.us-west-2.amazonaws.com/openchoreo-poc:default-doclet-document-svc-v1-696a9dc7
  dependencies:
    resources:
    - envBindings:
        url: DOCLET_DATABASE_URL
      ref: doclet-postgres
    - envBindings:
        url: DOCLET_NATS_URL
      ref: doclet-nats
  endpoints:
    http:
      port: 8080
      type: HTTP
      visibility:
      - project
      - external
  owner:
    componentName: document-svc
    projectName: doclet

